FROM openjdk:17-jdk-alpine
MAINTAINER codebyarunyadav.com
COPY target/spring-user-docker-0.0.1-SNAPSHOT.jar spring-user-docker-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/spring-user-docker-0.0.1-SNAPSHOT.jar"]